# Generated by Django 4.2.30 on 2026-04-10 16:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pipelinerun',
            name='name',
        ),
        migrations.RemoveField(
            model_name='pipelinerun',
            name='started_at',
        ),
        migrations.AddField(
            model_name='pipelinerun',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pipelinerun',
            name='dag_id',
            field=models.CharField(default='etl_pipeline', max_length=100),
        ),
        migrations.AddField(
            model_name='pipelinerun',
            name='dag_run_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pipelinerun',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='pipelinerun',
            name='status',
            field=models.CharField(max_length=50),
        ),
    ]
