# Generated by Django 4.2.30 on 2026-04-10 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_remove_pipelinerun_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipelinerun',
            name='dag_run_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
