# Generated by Django 4.2.30 on 2026-04-13 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_alter_pipelinerun_dag_run_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelinerun',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
